name: free-build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Set up Python 3.8
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: "3.8"
    #     cache: 'pip' # cache for faster build
    # - name: Update pip
    #   run: |
    #     python -m pip install --upgrade pip
    # - name: Install package
    #   run: |
    #     pip install -e .
    # - name: Install dependencies
    #   run: |
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # - name: Install benchmark package
    #   run: |
    #     pip install -r requirements_benchmark.txt
    # - name: Benchmark test
    #   run: |
    #     python cvxpy/benchmarks/run_benchmarks.py

    - name: commit
      run: |
        date > generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push https://${{ secrets.GITHUB_PAT }}@github.com/${{ github.actor }}/cvxpy.git HEAD:${{ github.head_ref }}
        
    # git remote add dev git@github.com:${{ github.actor }}/cvxpy.git
    # git push dev HEAD:${{ github.head_ref }}

  # # dummy create file
  #   - name: Create file
  #     run: |
  #       touch cvxpy/benchmarks/benchmark_report.md

  # commit:
  #   needs: benchmark
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
          # git add -f cvxpy/benchmarks/benchmark_report.md
# 
    # - name: Commit files # transfer the new html files back into the repository
    #   run: |
    #     date > generated.txt
    #     git config --local user.name "benchmarkjob"
    #     git add -f .
    #     git commit -m "Updating benchmark result"
    #     git push https://${{ secrets.GITHUB_PAT }}@github.com/${{ github.actor }}/cvxpy.git
    # - name: Push changes # push the output folder to your repo
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     repository: git@github.com:${{ github.actor }}/cvxpy
    #     branch: ${{ github.head_ref }}

