name: free-build

on:
  push:
    branches: [ benchmark2 ]
  pull_request:
    branches: [ benchmark2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install dependencies
      run: |
        pip install pytest
    - name: Test with pytest
      run: |
        pytest

    # - name: Commit files # transfer the new html files back into the repository
    #   run: |
    #     git config --local user.name "jpadfield"
    #     git add ./docs
    #     git commit -m "Updating the repository GitHub html pages in the docs folder"
    # - name: Push changes # push the output folder to your repo
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     force: true
